rules:
  responses-minimum-two:
    description: The responses field should contain at least two values.
    message: "{{property}} should contain at least two values."
    severity: error
    given: $.paths[*].get.responses
    then:
      function: length
      functionOptions:
        min: 2
